import {spawn} from 'node:child_process';
import {mkdir,writeFile} from 'node:fs/promises';
import path from 'node:path';
const [gallery,world,output]=process.argv.slice(2);
if(!gallery||!world||!output)throw Error('Usage: browser-smoke.mjs <creator-base-url> <world-base-url> <output-dir>');
await mkdir(output,{recursive:true});
const chrome=process.env.CHROME_PATH||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
const browser=spawn(chrome,['--headless','--disable-gpu','--no-first-run','--no-default-browser-check','--remote-debugging-port=0','--window-size=1440,1000',`--user-data-dir=${path.resolve(output,'profile')}`,'about:blank'],{stdio:['ignore','ignore','pipe'],windowsHide:true});
let stderr='';const ws=await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Chrome startup timeout')),10000);browser.stderr.on('data',b=>{stderr+=b;const m=stderr.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(m){clearTimeout(timer);resolve(m[1]);}});browser.once('exit',()=>reject(Error('Chrome exited')));});
const http=ws.replace('ws://','http://').replace(/\/devtools\/browser\/.*$/,'');
const target=await fetch(http+'/json/new?about:blank',{method:'PUT'}).then(r=>r.json());
const socket=new WebSocket(target.webSocketDebuggerUrl);await new Promise(r=>socket.onopen=r);
let id=0;const pending=new Map(),errors=[];
socket.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails.text);};
const cdp=(method,params={})=>new Promise((resolve,reject)=>{pending.set(++id,{resolve,reject});socket.send(JSON.stringify({id,method,params}));});
const evaluate=async expression=>(await cdp('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true})).result.value;
const wait=async expression=>{for(let i=0;i<100;i++){if(await evaluate(expression))return;await new Promise(r=>setTimeout(r,200));}throw Error('Timed out: '+expression);};
const screenshot=async name=>{const shot=await cdp('Page.captureScreenshot',{format:'png'});await writeFile(path.join(output,name+'.png'),Buffer.from(shot.data,'base64'));};
const results={};
try{
  await cdp('Page.enable');await cdp('Runtime.enable');
  await cdp('Page.navigate',{url:gallery});await wait("document.querySelectorAll('.builder').length>0");
  results.directory=await evaluate("({title:document.title,cards:document.querySelectorAll('.builder').length,status:document.getElementById('status').textContent})");await screenshot('creators');
  await evaluate("document.getElementById('search').value='__no_such_builder_928478__';document.getElementById('search').dispatchEvent(new Event('input'))");
  if(await evaluate("document.querySelectorAll('.builder').length")!==0)throw Error('Builder search did not filter');
  const directory=await fetch(new URL('directory.json',gallery)).then(r=>r.json());
  const photographed=directory.builders.filter(b=>b.photos>0&&b.eras.length>1).sort((a,b)=>b.photos-a.photos)[0];
  if(!photographed)throw Error('No cross-era photographed builder');
  await cdp('Page.navigate',{url:new URL(photographed.builderKey+'/',gallery).href});
  await wait("document.querySelectorAll('.photos img').length>0");
  results.thread=await evaluate("({title:document.getElementById('title').textContent,eras:document.querySelectorAll('details').length,photos:document.querySelectorAll('.photos img').length})");
  await wait("[...document.querySelectorAll('.photos img')].filter(i=>i.loading!=='lazy'||i.getBoundingClientRect().top<innerHeight).every(i=>i.complete&&i.naturalWidth>0)");await screenshot('creator-thread');
  await cdp('Page.navigate',{url:new URL('?era=era7&build='+'a'.repeat(64),world).href});
  await wait("document.querySelector('.workspace h1')?.textContent.includes('Terrain preparation pending')");
  if(await evaluate("document.querySelectorAll('.context-raster').length")!==0)throw Error('Pending era displayed stale terrain');
  results.pending=await evaluate("document.querySelector('.workspace h1').textContent");await screenshot('pending-era');
  await evaluate("document.getElementById('era-select').value='era17';document.getElementById('era-select').dispatchEvent(new Event('change'))");
  await wait("[...document.querySelectorAll('.context-raster')].some(i=>i.complete&&i.naturalWidth>0)");
  if(await evaluate("new URLSearchParams(location.search).has('build')"))throw Error('Era switch retained previous build');
  results.switch=await evaluate("({era:document.getElementById('era-select').value,context:document.querySelector('.context-raster').src,world:document.getElementById('public-world-name').textContent})");
  if(!new URL(results.switch.context).searchParams.get('era'))throw Error('Terrain request lost era scope');
  await screenshot('era17');
  if(errors.length)throw Error(errors.join('\n'));
  results.status='passed';await writeFile(path.join(output,'receipt.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results,null,2));
}finally{socket.close();browser.kill();}
