#!/usr/bin/env python3
"""Rank prefab representation edge cases without changing any representation.

The report combines snapshot frequency, suspicious unit/default bounds, extreme or
degenerate envelopes, and real selfie-stick gallery coverage. Gallery membership is
an exact X/Z containment join over gallery cluster scopes; photographs stay in place.
"""
from __future__ import annotations

import argparse
import json
import math
from collections import Counter, defaultdict
from pathlib import Path

import duckdb

GRID_METERS = 128.0
SEED_PATTERNS = {
    "current-candidate": ("windmill",),
    "production": ("smelter", "charcoal_kiln", "blastfurnace"),
    "ships": ("karve", "vikingship", "raft"),
    "banners-rugs": ("banner", "rug"),
    "roof-wedges": ("roof",),
    "vegetation": ("tree", "bush", "shrub", "vines", "sapling"),
}


def load(path: Path) -> dict:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def cell(value: float) -> int:
    return math.floor(value / GRID_METERS)


def base_features(piece: dict) -> dict:
    extents = [float(value) for value in piece["extents"]]
    volume = math.prod(max(value, 0.01) for value in extents)
    unit_default = all(abs(value - 1.0) < 1e-6 for value in extents) or \
        piece.get("center_source") == "family_default"
    extreme = max(extents) > 20 or volume > 2_000
    degenerate = min(extents) < 0.02
    count = int(piece.get("count_era17", 0))
    score = math.log10(count + 1) * 18 + unit_default * 45 + extreme * 50 + degenerate * 25
    return {
        "name": piece["name"], "hash": int(piece["hash"]), "family": piece["family"],
        "count": count, "extents": extents, "volumeM3": round(volume, 3),
        "geometrySource": piece["source"], "unitOrDefault": unit_default,
        "extreme": extreme, "degenerate": degenerate, "score": score,
    }


def gallery_coverage(rows: list[dict], gallery_index: dict, clusters_root: dict,
                     parquet: Path, candidate_limit: int) -> None:
    images_per_cluster = Counter(int(image["cluster_id"]) for image in gallery_index["images"]
                                 if image.get("cluster_id") is not None)
    cluster_by_id = {int(item["cluster_id"]): item for item in clusters_root["clusters"]}
    scopes = {cluster_id: cluster_by_id[cluster_id] for cluster_id in images_per_cluster
              if cluster_id in cluster_by_id}
    spatial = defaultdict(list)
    for cluster_id, scope in scopes.items():
        for gx in range(cell(float(scope["min_x"])), cell(float(scope["max_x"])) + 1):
            for gz in range(cell(float(scope["min_z"])), cell(float(scope["max_z"])) + 1):
                spatial[(gx, gz)].append(cluster_id)

    selected = rows[:candidate_limit]
    seeds = {row["name"] for row in rows if any(
        pattern in row["name"].lower() for patterns in SEED_PATTERNS.values() for pattern in patterns)}
    names = {row["name"] for row in selected} | seeds
    connection = duckdb.connect()
    connection.execute("CREATE TEMP TABLE candidates(name VARCHAR)")
    connection.executemany("INSERT INTO candidates VALUES (?)", [(name,) for name in sorted(names)])
    coordinates = connection.execute(
        """SELECT prefab_name, x, z FROM read_parquet(?)
           SEMI JOIN candidates ON prefab_name = name WHERE category = 'BUILDING'""",
        [str(parquet)],
    ).fetchall()
    covered = defaultdict(set)
    for name, x, z in coordinates:
        for cluster_id in spatial.get((cell(float(x)), cell(float(z))), ()):
            scope = scopes[cluster_id]
            if float(scope["min_x"]) <= x <= float(scope["max_x"]) and \
                    float(scope["min_z"]) <= z <= float(scope["max_z"]):
                covered[name].add(cluster_id)
    for row in rows:
        cluster_ids = covered.get(row["name"], set())
        row["galleryClusters"] = len(cluster_ids)
        row["galleryViews"] = sum(images_per_cluster[value] for value in cluster_ids)
        row["score"] += min(35, math.log2(row["galleryViews"] + 1) * 6)


def seed_group(name: str) -> str | None:
    lowered = name.lower()
    for group, patterns in SEED_PATTERNS.items():
        if any(pattern in lowered for pattern in patterns):
            return group
    return None


def markdown(rows: list[dict], top: int) -> str:
    lines = [
        "# Prefab fidelity backlog — snapshot 107",
        "",
        "Generated by `tools/rank-prefab-fidelity.py`. Ranking is triage, not promotion: no row below",
        "changes the runtime catalog. Gallery coverage counts matched private cluster/view receipts without",
        "copying source images.", "",
        "## Highest-priority representation risks", "",
        "| Rank | Prefab | Placed | Bounds (m) | Signals | Gallery clusters / views |",
        "|---:|---|---:|---|---|---:|",
    ]
    for index, row in enumerate(rows[:top], 1):
        signals = ", ".join(label for label, present in (
            ("unit/default", row["unitOrDefault"]), ("extreme", row["extreme"]),
            ("degenerate", row["degenerate"])) if present) or "frequency"
        bounds = " × ".join(f"{value:g}" for value in row["extents"])
        lines.append(f"| {index} | `{row['name']}` | {row['count']:,} | {bounds} | {signals} | "
                     f"{row['galleryClusters']} / {row['galleryViews']} |")
    lines += ["", "## Deliberately unmodified seed families", "",
              "These are evidence-backed next comparisons, not substring rules in the runtime renderer.", "",
              "| Family | Representative prefabs (highest snapshot frequency first) |", "|---|---|"]
    for group in SEED_PATTERNS:
        matches = sorted((row for row in rows if seed_group(row["name"]) == group),
                         key=lambda row: (-row["count"], row["name"]))[:12]
        lines.append(f"| {group} | " + ", ".join(
            f"`{row['name']}` ({row['count']:,}; {row['galleryViews']} views)" for row in matches) + " |")
    lines += ["", "## Reading the score", "",
              "Frequency raises impact; unit/default, extreme, and degenerate bounds raise representation risk;",
              "gallery coverage raises testability. Promotion still requires a renderer receipt plus tuning and",
              "holdout metrics. Fires, furniture, logs, and stumps are intentionally not reclassified as context.", ""]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--geometry", type=Path, required=True)
    parser.add_argument("--gallery-index", type=Path, required=True)
    parser.add_argument("--clusters", type=Path, required=True)
    parser.add_argument("--parquet", type=Path, required=True)
    parser.add_argument("--out-json", type=Path, required=True)
    parser.add_argument("--out-markdown", type=Path, required=True)
    parser.add_argument("--candidate-limit", type=int, default=300)
    parser.add_argument("--top", type=int, default=30)
    args = parser.parse_args()

    rows = [base_features(piece) for piece in load(args.geometry)["pieces"]]
    rows.sort(key=lambda row: (-row["score"], -row["count"], row["name"]))
    gallery_coverage(rows, load(args.gallery_index), load(args.clusters), args.parquet,
                     args.candidate_limit)
    rows.sort(key=lambda row: (-row["score"], -row["count"], row["name"]))
    output = {"schema": "steward-prefab-fidelity-backlog/v1", "snapshotId": 107,
              "rankingOnly": True, "rows": rows}
    args.out_json.parent.mkdir(parents=True, exist_ok=True)
    args.out_markdown.parent.mkdir(parents=True, exist_ok=True)
    args.out_json.write_text(json.dumps(output, indent=2) + "\n", encoding="utf-8")
    args.out_markdown.write_text(markdown(rows, args.top), encoding="utf-8")
    print(f"ranked {len(rows)} prefabs; wrote {args.out_json} and {args.out_markdown}")


if __name__ == "__main__":
    main()
